---
openapi: 3.0.3
info:
  title: onecx-parameters-bff
  description: OneCx parameters Bff
  version: '2.0'
servers:
  - url: http://onecx-parameters-bff:8080/
tags:
  - name: histories
  - name: parameters
paths:
  /histories:
    post:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - histories
      description: Find all parameters history
      operationId: getAllApplicationParametersHistory
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationParameterHistoryCriteria'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationParameterHistoryPageResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /histories/counts:
    post:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - histories
      description: Get creation dates and counts by criteria
      operationId: getCountsByCriteria
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ParameterHistoryCountCriteria'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ParameterHistoryCount'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /histories/latest:
    post:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - histories
      description: Find all parameters history latest
      operationId: getAllApplicationParametersHistoryLatest

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationParameterHistoryCriteria'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationParameterHistoryPageResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /histories/{id}:
    get:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - histories
      description: Find parameters history by Id
      operationId: getApplicationParametersHistoryById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationParameterHistory'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: Not Found
  /parameters:
    get:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - parameters
      description: Find all parameters
      operationId: getAllApplicationParameters
      parameters:
        - name: applicationId
          in: query
          schema:
            description: The application parameter id.
            type: string
        - name: productName
          in: query
          schema:
            description: The product name.
            type: string
        - name: key
          in: query
          schema:
            description: The application parameter key.
            type: string
        - name: name
          in: query
          schema:
            description: The application parameter name.
            type: string
        - name: pageNumber
          in: query
          schema:
            format: int32
            description: The number of page.
            default: 0
            type: integer
        - name: pageSize
          in: query
          schema:
            format: int32
            description: The size of page
            default: 100
            type: integer
        - name: type
          in: query
          schema:
            description: The application parameter type.
            type: array
            items:
              type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationParameterPageResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
    post:
      x-onecx:
        permissions:
          parameter:
            - write
      tags:
        - parameters
      description: Create parameter
      operationId: createParameterValue
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationParameterCreate'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: Not Found
  /parameters/applications:
    get:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - parameters
      description: Find all parameters
      operationId: getAllApplications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationsPageResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /parameters/keys:
    get:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - parameters
      description: Find all parameters
      operationId: getAllKeys
      parameters:
        - name: applicationId
          in: query
          schema:
            description: The application parameter id.
            type: string
        - name: productName
          in: query
          schema:
            description: The product name.
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/KeysPageResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
  /parameters/{id}:
    get:
      x-onecx:
        permissions:
          parameter:
            - read
      tags:
        - parameters
      description: Find parameter by id
      operationId: getParameterById
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApplicationParameter'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: Not Found
    put:
      x-onecx:
        permissions:
          parameter:
            - write
      tags:
        - parameters
      description: Update parameter
      operationId: updateParameterValue
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApplicationParameterUpdate'
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
        '404':
          description: Not Found
    delete:
      x-onecx:
        permissions:
          parameter:
            - delete
      tags:
        - parameters
      description: Delete parameter
      operationId: deleteParameter
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetailResponse'
components:
  schemas:
    ApplicationParameterCreate:
      type: object
      properties:
        key:
          type: string
        applicationId:
          type: string
        productName:
          type: string
        value:
          type: string
        type:
          type: string
        description:
          type: string
        unit:
          type: string
        rangeFrom:
          format: int32
          type: integer
        rangeTo:
          format: int32
          type: integer
    ApplicationParameter:
      type: object
      properties:
        id:
          type: string
        modificationCount:
          format: int32
          type: integer
        creationDate:
          format: date-time
          type: string
          example: 2022-03-10T12:15:50-04:00
        creationUser:
          type: string
        modificationDate:
          format: date-time
          type: string
          example: 2022-03-10T12:15:50-04:00
        modificationUser:
          type: string
        name:
          type: string
        description:
          type: string
        applicationId:
          type: string
        productName:
          type: string
        key:
          type: string
        setValue:
          type: string
        importValue:
          type: string
        type:
          type: string
        unit:
          type: string
        rangeFrom:
          format: int32
          type: integer
        rangeTo:
          format: int32
          type: integer
    ApplicationParameterHistory:
      type: object
      properties:
        id:
          type: string
        modificationCount:
          format: int32
          type: integer
        creationDate:
          format: date-time
          type: string
          example: 2022-03-10T12:15:50-04:00
        creationUser:
          type: string
        modificationDate:
          format: date-time
          type: string
          example: 2022-03-10T12:15:50-04:00
        modificationUser:
          type: string
        applicationId:
          type: string
        productName:
          type: string
        key:
          type: string
        usedValue:
          type: string
        defaultValue:
          type: string
        type:
          type: string
        instanceId:
          type: string
    ApplicationParameterHistoryCriteria:
      type: object
      properties:
        applicationId:
          type: string
        productName:
          type: string
        key:
          type: string
        pageNumber:
          type: integer
          format: int32
          default: 0
        pageSize:
          type: integer
          format: int32
          default: 100
        type:
          type: array
          items:
            type: string
    ApplicationParameterHistoryPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationParameterHistory'
    ApplicationParameterPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            $ref: '#/components/schemas/ApplicationParameter'
    ApplicationParameterUpdate:
      type: object
      properties:
        value: {}
        description:
          type: string
        unit:
          type: string
        rangeFrom:
          format: int32
          type: integer
        rangeTo:
          format: int32
          type: integer
    ApplicationsPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            type: string
    KeysPageResult:
      type: object
      properties:
        totalElements:
          format: int64
          description: The total elements in the resource.
          type: integer
        number:
          format: int32
          type: integer
        size:
          format: int32
          type: integer
        totalPages:
          format: int64
          type: integer
        stream:
          type: array
          items:
            type: string
    ParameterHistoryCountCriteria:
      type: object
      properties:
        applicationId:
          type: string
        productName:
          type: string
        key:
          type: string
        pageNumber:
          format: int32
          default: 0
          type: integer
        pageSize:
          format: int32
          default: 100
          type: integer
        type:
          type: array
          items:
            type: string
    ParameterHistoryCount:
      type: object
      properties:
        creationDate:
          format: date-time
          type: string
          example: 2022-03-10T12:15:50
        count:
          format: int64
          type: integer
    ProblemDetailResponse:
      type: object
      properties:
        errorCode:
          type: string
        detail:
          type: string
        params:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailParam'
        invalidParams:
          type: array
          items:
            $ref: '#/components/schemas/ProblemDetailInvalidParam'
    ProblemDetailParam:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    ProblemDetailInvalidParam:
      type: object
      properties:
        name:
          type: string
        message:
          type: string
